### ISSUE TITLE
Training script for ff2

### ISSUE THREAD

**Issue by OliviaViessmann** [DreamFold/FoldFlow#15]
Hi,

great work on FF2 -- I would love to replicate it, but the trianing script provided is for the previous version. 
Would it be possible to provide the training script and configs for FF2?
I see that that model modules are all there. 

Thanks
Olivia

**Comment by stanislav-chekmenev** [comment]
Hi @OliviaViessmann. I'm building on top of FF2 model and faced the same issue, but it's easily fixable cause all you need to have is right there. You need to change (or create a new hydra config file that would have "ff2" for the "model" field. I have something like that for the main `base.yaml` config file :

```yaml
# Default or base configuration for SE(3) Flow Matcher experiments.
defaults:
  - data: data_test
  - flow_matcher: fm_test
  - model: ff2
  - experiment: exp_test
  - local: ff2_debug
  - wandb: default
  - override hydra/launcher: joblib
  - _self_

    # start_time_string: ${now:%Y-%m-%d}_${now:%H-%M-%S}
start_time_string: "default"
conda_env: foldflow-env
```

Then, there are minor changes in the `runner/train.py` and `runner/inference.py`. You can check them out in my fork of the repo and just use it. Here's the fork:

https://github.com/stanislav-chekmenev/foldflow

I checked only training (well, it trains on 1 protein on my local machine), but I haven't tested my version of the inference script and training from checkpoints, though the changes I made are small and the whole thing about loading from checkpoints is rather not complicated to fix if needed.
